# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecomparison',
            options={'permissions': (('export_comparison_branch', 'Can export comparison branch as a layer'),)},
        ),
    ]
