# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-25 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layerindex', '0028_branch_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagecomparison_from_set', to='layerindex.Branch')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagecomparison_to_set', to='layerindex.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageComparisonRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layerindex.Recipe')),
                ('cover_pn', models.CharField(blank=True, max_length=100, verbose_name='Covering recipe')),
                ('cover_status', models.CharField(choices=[('U', 'Unknown'), ('N', 'Not available'), ('S', 'Distro-specific'), ('O', 'Obsolete'), ('E', 'Equivalent functionality'), ('D', 'Direct match')], default='U', max_length=1)),
                ('cover_comment', models.TextField(blank=True)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layerindex.ImageComparison')),
                ('cover_layerbranch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layerindex.LayerBranch', verbose_name='Covering layer')),
            ],
            bases=('layerindex.recipe',),
        ),
        migrations.AlterUniqueTogether(
            name='imagecomparison',
            unique_together=set([('user', 'name')]),
        ),
    ]
