# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0032_patchdisposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versioncomparison_from_set', to='layerindex.Branch')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versioncomparison_to_set', to='layerindex.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='VersionComparisonDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=100)),
                ('change_type', models.CharField(choices=[('A', 'Add'), ('U', 'Upgrade'), ('D', 'Downgrade'), ('V', 'Version changes'), ('R', 'Remove'), ('M', 'Modification')], max_length=1)),
                ('oldvalue', models.CharField(blank=True, max_length=255)),
                ('newvalue', models.CharField(blank=True, max_length=255)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layerindex.VersionComparison')),
                ('from_layerbranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versioncomparisondifference_from_set', to='layerindex.LayerBranch')),
                ('to_layerbranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versioncomparisondifference_to_set', to='layerindex.LayerBranch')),
            ],
        ),
    ]
