# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-02 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0034_source_sha256sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionComparisonFileDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('I', 'In progress'), ('F', 'Failed'), ('S', 'Succeeded')], default='I', max_length=1)),
                ('difference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layerindex.VersionComparisonDifference')),
            ],
        ),
    ]
