# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-03 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0038_patch_striplevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicrecipe',
            name='sha256sum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patch',
            name='sha256sum',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
