# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-05 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0039_comparison_sha256sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncomparison',
            name='status',
            field=models.CharField(choices=[('I', 'In progress'), ('F', 'Failed'), ('S', 'Succeeded')], default='I', max_length=1),
        ),
    ]
