# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-06 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0044_dissector')
    ]

    operations = [
        migrations.AddField(
            model_name='classicrecipe',
            name='export',
            field=models.CharField(choices=[('X', 'Export'), ('A', 'Already handled'), ('N', 'Not needed')], default='X', max_length=1),
        ),
    ]
