# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0045_classicrecipe_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicrecipe',
            name='export_class',
            field=models.CharField(choices=[('T', 'Target only'), ('A', 'All')], default='T', max_length=1),
        ),
    ]
