# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0049_savedsearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['recipe', 'index']},
        ),
        migrations.AddField(
            model_name='source',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
