# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0050_source_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patchdisposition',
            options={'permissions': (('patch_disposition', 'Can disposition patches'), ('patch_disposition_view', 'Can view patch dispositioning'))},
        ),
    ]
